[tool.poetry]
name = "remerge"
version = "0.1.0"
description = ""
authors = ["Peter Baumgartner <5107405+pmbaumgartner@users.noreply.github.com>"]
readme = "README.md"
packages = [{include = "remerge", from = "src"}]

[tool.poetry.dependencies]
python = "^3.8"
tqdm = "^4.64.1"
numpy = ">=1.18,<1.23"


[tool.poetry.group.dev.dependencies]
pytest = "^7.1.3"
ipython = "^8.5.0"
black = "^22.8.0"
flake8 = "^5.0.4"
mypy = "^0.981"
py-spy = "^0.3.14"
pytest-sugar = "^0.9.5"
pytest-cov = "^4.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
